import Head from "next/head";
import Navbar from "../components/Navbar";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        </style>
      </head>
      <body className="bg-body">
				<Navbar name="asd"/>
        {/* <span className="font-bold text-blue-600">Giuro</span> */}
      </body>
    </>
  );
}
